#!/bin/bash

if [ "$1" = "" ]; then
  echo "CRITICAL - Missing hostname as argument"
  exit 2
elif [[ $(command -v curl >/dev/null 2>&1) -ne "0" ]]; then
  echo "CRITICAL - Curl is missing"
  exit 2
fi

STATUS=$(curl --silent --show-error --head --location $1 2>&1)

if [ $? -ne 0 ]; then
  echo "CRITICAL - $STATUS"
  exit 2
fi

CODE=$(echo $STATUS | grep HTTP | cut -d ' ' -f 2)

case $CODE in
  200|401)
    echo "OK - Rancher server is responding"
    exit 0
  ;;
  *)
    echo "CRITICAL - $STATUS"
    exit 2
  ;;
esac
